# python tutorial
'''
comments -- the basics -- before we get fancy we should use
1) decent algorithms
2) builit ins
3) well documented and tested libraries
4) Reinvent the wheel
'''


print "===================================="
print "abs()"
print "abs(-5) absolute value of a number, gives %s, error if not number" % abs(-5)
print "===================================="
print "all()"
print "all(x) is true if all x, which is a iterable, is true"
x = [1,2,3,4,5,6,7,8]
print all(x)
x = [1,2,3,4,5,6,7,0]
print all(x)
print "===================================="
print "any()"
print "any(x) is true if any x, which is a iterable, is true"
x = [1,2,3,4,5,6,7,8]
print any(x)
x = []
print any(x)
print "===================================="
print "basestring()"
print "===================================="
print "bin()"
print "Convert an integer number to a binary string"
print "bin(4) gives %s , a binary string and is type %s" % (bin(4), type(bin(4)))
print "===================================="
print "bool()"
print "===================================="
print "bytearray()"
print "===================================="
print "callable()"
print "===================================="
print "chr()"
print "===================================="
print "classmethod()"
print "===================================="
print "cmp()"
print "===================================="
print "compile()"
print "===================================="
print "complex()"
print "===================================="
print "delattr()"
print "===================================="
print "dict()"
print "===================================="
print "dir()"
print "===================================="
print "divmod()"
print "===================================="
print "enumerate()"
print "===================================="
print "eval()"
print "===================================="
print "execfile()"
print "===================================="
print "file()"
print "===================================="
print "filter()"
print "===================================="
print "float()"
print "===================================="
print "format()"
print "===================================="
print "frozenset()"
print "===================================="
print "getattr()"
print "===================================="
print "globals()"
print "===================================="
print "hasattr()"
print "===================================="
print "hash()"
print "===================================="
print "help()"
print "===================================="
print "hex()"
print "===================================="
print "id()"
print "===================================="
print "input()"
print "===================================="
print "int()"
print "===================================="
print "isinstance()"
print "===================================="
print "issubclass()"
print "===================================="
print "iter()"
print "===================================="
print "len()"
print "===================================="
print "list()"
print "===================================="
print "locals()"
print "===================================="
print "long()"
print "===================================="
print "map()"
print "===================================="
print "max()"
print "===================================="
print "memoryview()"
print "===================================="
print "min()"
print "===================================="
print "next()"
print "===================================="
print "object()"
print "===================================="
print "oct()"
print "===================================="
print "open()"
print "===================================="
print "ord()"
print "===================================="
print "pow()"
print "===================================="
print "print()"
print "===================================="
print "property()"
print "===================================="
print "range()"
print "===================================="
print "raw_input()"
print "===================================="
print "===================================="
print "reduce()"
print "===================================="
print "reload()"
print "===================================="
print "repr()"
print "===================================="
print "reversed()"
print "===================================="
print "round()"
print "===================================="
print "set()"
print "===================================="
print "setattr()"
print "===================================="
print "slice()"
print "===================================="
print "sorted()"
print "===================================="
print "staticmethod()"
print "===================================="
print "str()"
print "===================================="
print "sum()"
print "===================================="
print "super()"
print "===================================="
print "tuple()"
print "===================================="
print "type()"
print "===================================="
print "unichr()"
print "===================================="
print "unicode()"
print "===================================="
print "vars()"
print "===================================="
print "xrange()"
print "===================================="
print "zip()"
print "===================================="
print "__import__()"
print "===================================="
print "apply()"
print "===================================="
print "buffer()"
print "===================================="
print "coerce()"
print "===================================="
print "intern()"
print "===================================="